Explainer updates for clarity, grammar, and URL localization
WICG/translation-api pull request #17
Opened 2024-08-26 14:17 UTC by alexandrascript

This PR fixes a spelling error, suggests changes for clarity in certain parts of the explainer, and removes English/US-based URL structure from links so that readers are directed to a localized URL.

2024-08-26 23:35 UTC, domenic commented
The spelling changes and URLs are reasonable, but please don't insert your personal style choices here (e.g. abbreviations vs. not).

2024-08-27 00:21 UTC, KenjiBaheux commented
I caught an extra one: "support for combining the langauge detection" => language.

2024-08-27 18:02 UTC, alexandrascript commented
@domenic I've reverted some of the suggestions, which reflect Google's style guide, but I know don't have to apply here.

However, I've kept the changes to the paragraph on line 380. The original paragraph was missing clarity--some is easy to define, such as the pronouns. A less prescriptive example is the change to "which did"--this sentence fragment would be better understood as "with" because it's reflective of what's being "included" in the earlier version.

2024-08-27 19:28 UTC, domenic requested changes

2024-08-27 19:28 UTC, domenic commented on README.md
> +* Help web developers perform real-time translations (e.g., of user input).
Please revert

2024-08-27 19:28 UTC, domenic commented on README.md
> +* Allow web developers to know whether translation is done on-device or using cloud services. This would allow them to guarantee that any user data they feed into this API does not leave the device,
Please revert

2024-08-27 19:28 UTC, domenic commented on README.md
> +An earlier version of this API included support for combining the langauge detection and translation steps into a single translation call, with a best-guess on the source language. The idea implied t
Please revert

2024-09-05 16:27 UTC, Thapeloza approved these changes
```
```
- - [ ] 
```
```

2024-10-09 04:15 UTC, closed without merging